export const weatherCondition: { [key: number]: string } = {
  0: 'Langit cerah',
  1: 'Agak cerah',
  2: 'Setengah berawan',
  3: 'Penuh awan',
  45: 'Berkabut',
  48: 'Kabut beku',
  51: 'Gerimis tipis',
  53: 'Gerimis biasa',
  55: 'Gerimis tebal',
  56: 'Gerimis dingin',
  57: 'Gerimis beku',
  61: 'Hujan ringan',
  63: 'Hujan sedang',
  65: 'Hujan deras',
  66: 'Hujan beku',
  67: 'Hujan beku deras',
  71: 'Salju tipis',
  73: 'Salju sedang',
  75: 'Salju tebal',
  77: 'Serpihan salju',
  80: 'Hujan sebentar',
  81: 'Hujan agak deras',
  82: 'Hujan super deras',
  85: 'Salju sebentar',
  86: 'Salju deras sebentar',
  95: 'Petir kecil',
  96: 'Petir plus es',
  99: 'Petir ganas es',
  // 0: 'Clear sky',
  // 1: 'Mostly clear',
  // 2: 'Partly cloudy',
  // 3: 'Overcast',
  // 45: 'Fog',
  // 48: 'Rime fog',
  // 51: 'Light drizzle',
  // 53: 'Moderate drizzle',
  // 55: 'Dense drizzle',
  // 56: 'Light freezing drizzle',
  // 57: 'Dense freezing drizzle',
  // 61: 'Light rain',
  // 63: 'Moderate rain',
  // 65: 'Heavy rain',
  // 66: 'Light freezing rain',
  // 67: 'Heavy freezing rain',
  // 71: 'Light snow',
  // 73: 'Moderate snow',
  // 75: 'Heavy snow',
  // 77: 'Snow grains',
  // 80: 'Light rain showers',
  // 81: 'Moderate rain showers',
  // 82: 'Violent rain showers',
  // 85: 'Light snow showers',
  // 86: 'Heavy snow showers',
  // 95: 'Light thunderstorm',
  // 96: 'Thunderstorm with hail',
  // 99: 'Heavy thunderstorm hail',
}
